import type { Metadata } from 'next';

import { pretendard } from '@/libs/fonts';
import CustomThemeProvider from '@/provider/CustomThemeProvider';
import ReactQueryProvider from '@/provider/ReactQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <CustomThemeProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
